from .signup import signup
from .login import login
from .client import client_router
from .discount import discount_router
from .service import service_router
from .chofer import chofer_router
from .general import general_router
from .admin import admin_router
from .ticket import ticket_router
from .transaccion import transaccion_router
